# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
